### ISSUE TITLE
Add proper support for eth_hashrate

### ISSUE THREAD

**Issue by timbeiko** [hyperledger/besu#1019]
We should properly support `eth_hashrate`, as it currently always returns 0. 

We need to add eth_submitHashrate that is just a two arg function, a BigInteger first arg (value) and a hash as second arg (key) and we put it in a hashmap.  Then for eth_hashrate we sum up the values of the map with the cpu rate.  

We may want to size limit the hashmap (where we evict the least recently updated value) and remove zero rates to prevent memory bloat attacks.

**Comment by RatanRSur** [comment]
If we always return 0, does this count as a bug?

**Comment by matkt** [comment]
> If we always return 0, does this count as a bug?

I would say it’s an improvement rather than a bug

**Comment by matkt** [comment]
In progress ...

# Implementation
- Implemented `submitHashrate` endpoint which is by default limited to 1000 sealers. Adding a 1001 will remove the oldest from the list (0x0 hashrate is refused)
- Updated `eth_hashrate`endpoint so that it returns the cumulative hashrate of all sealers if the list is not empty. Otherwise it returns the local hashrate
- Added hashrate submission with `Stratum1EthProxyProtocol` and` Stratum1Protocol`

# Test
- Tested the hashrate submission with ethminer `sudo ethminer -G -P stratum + tcp: //127.0.0.1: 8008 --report-hashrate`
- Tested the json rpc api 
````
{"id":1,"jsonrpc":"2.0","method":"eth_submitHashrate","params":["0x00","0x01"]}
````
````
{"id":1,"jsonrpc":"2.0","method":"eth_submitHashrate","params":["0x01","0x01"]}
````
# ToDo
- Test with Phoenix
- Test with EthProxy
- Add CLI option to change the limited number of sealers
