### ISSUE TITLE
Fix flakey AT Ibft2ProposeRpcAcceptanceTest.validatorsCanBeAddedAndThenRemoved

### ISSUE THREAD

**Issue by RatanRSur** [hyperledger/besu#1023]
Logs here:
[6.txt](https://github.com/hyperledger/besu/files/4720250/6.txt)

**Comment by RatanRSur** [comment]
@rain-on So once I got the out of memory issue fixed, it turns out that it's failing for real now. Because of the dreaded git blame, I assigned this to you but feel free to find whoever else you think is better suited to it.

**Comment by RatanRSur** [comment]
[6.txt](https://github.com/hyperledger/besu/files/4720249/6.txt)

**Comment by rain-on** [comment]
From a review of the log file, it appears that Validator1 stops importing blocks after #37 - which I believe is the first block to contain a proposal for "non-validator" - #38 would contain the second proposal.

Because Validator-1 stopped importing blocks, its internal tracking of validators would have also stopped - thus the failure we see (which is that Validator1 does not see a change in the validator pool).

The log file does not give any hints as to why Validator1 stopped importing blocks - but the node must still be running otherwise the JSON RPC requests to validator1 would fail with a socket error.

Final intersting point (red-herring) - at the end of the test, it can be seen that the validator1 process has already terminated.
