### ISSUE TITLE
Use SafeFuture to allow use of `FutureReturnValueIgnored` error prone check

### ISSUE THREAD

**Issue by RatanRSur** [hyperledger/besu#1113]
From @ajsutton:

In the spirit of knowledge sharing, Teku has introduced a SafeFuture class which extends CompletableFuture and provides a bunch of handy methods that CompletableFuture is missing. The primary factor for this was to allow us to enable errorprone’s FutureReturnValueIgnored check which ensures that exceptions within CompletableFuture chains are never lost because the returned future was ignored.  We’ve seen that a number of times in besu and teku so wanted to stamp it out. Most of the new methods center around that like reportExceptions which is basically like the thread’s exception handler - shouldn’t ever be called but at least logs the problem if something does go wrong.  But also some finish variants that make it easy to handle success or failure and not get yet another CompletableFuture back.
We’ve also recently added the ever-useful exceptionallyCompose.
https://github.com/PegaSysEng/teku/blob/5f0b0fae5cf5363fa7b751cdb53378ae1b3d1883/util/src/main/java/tech/pegasys/teku/util/async/SafeFuture.java
https://github.com/PegaSysEng/teku/blob/5f0b0fae5cf5363fa7b751cdb53378ae1b3d1883/util/src/test/java/tech/pegasys/teku/util/async/SafeFutureTest.java

**Comment by ajsutton** [comment]
Adding `SafeFuture` has turned out to be one of the best decisions we've made in Teku. It's grown quite a few really useful utility methods to make working with futures easier and fixed a *lot* of places where we would have lost exceptions.

There has been almost no cost to using it because you can pass a `SafeFuture` to anything that wants a `CompletableFuture` and anything that returns a `CompletableFuture` can easily be converted with `SafeFuture.of(CompletableFuture)`.
