### ISSUE TITLE
Smart Contract Account Permissions not checked on local transaction submission

### ISSUE THREAD

**Issue by magooster** [hyperledger/besu#1191]
### Description

Enabling smart contract based account permissioning results in transactions from non-allowed accounts filling the local nodes transaction pool.

### Steps to Reproduce (Bug)
1. Deploy smart contract based account permssioning (AccountIngress + Admin + AccountRules contracts)
2. Send multiple signed raw transactions from an address not in the contracts allowlist.

**Expected behavior:** [What you expect to happen]
Send raw transaction request should be rejected with a suitable error.

**Actual behavior:** [What actually happens]
Transaction submission succeeds but transaction fails to be confirmed (included in a block), and future transactions remain in the local nodes transaction pool. The first transaction (nonce 0) is 'silently' dropped.

**Frequency:** [What percentage of the time does it occur?]
Every time

### Versions (Add all that apply)
* Software version: 1.4.6

### Additional Information

It looks like the onchain permission checks don't run as part of the checks when adding a transaction to the local nodes pool.

**Comment by MadelineMurray** [comment]
hi @magooster - this is by design.  The reason behind this is that onchain permissioning rules can be updated while a transaction is being added to or is in the transaction pool. This means the transaction might be allowed by the time it is added to a block. 

When permissioning rules are applied for onchain and local permissioning is illustrated here: 
https://besu.hyperledger.org/en/stable/Concepts/Permissioning/Permissioning-Overview/#onchain 

The order transactions are dropped in is described here: https://besu.hyperledger.org/en/stable/Concepts/Transactions/Transaction-Pool/#dropping-transactions-when-the-transaction-pool-is-full 

Let me know if that doesn't make sense or this behaviour is causing specific issues for your use-case.

**Comment by magooster** [comment]
Thanks for the feedback, I was missing the content in the first link. Personally i'm not convinced  about the logic for when the checks are applied. The edge case for the reverse logic would be a transaction might be rejected after it has been accepted into the pool, at least the submitter would get 'feedback' at submission time.

Also in the scenario I describe above only the first transaction with the current sender nonce is evaluated against the contract permissions during block processing, the other transactions with future nonces pollute the pool, as the nonce validation occurs before the permissions validation. 

The only way those will get processed is if i) the sender manually fills in the nonce gap and ii) the sender address is added to the allow list. 

If the validation order were changed such that the permissions check occurs before the current nonce check  then those future transactions would not pollute the transactions pool. 

---

I don't have a specific use-case, but one problem with the current implementation is that an external system has no means to efficiently capture and respond to a permissions failure.  With local permissions on submission an error would be returned. With other contract based permissions I can add a revert and interrogate that. The permissioning contracts provide neither, happy to be corrected here...

Options with the current implementation I can see is to manually call the permissioning contract prior to submission, or sync the local permissions with the contract.

**Comment by MadelineMurray** [comment]
@lucassaldanha - I'm looking at this again and I think we should talk about these two points specifically in standup on Monday: 
> If the validation order were changed such that the permissions check occurs before the current nonce check then those future transactions would not pollute the transactions pool.

> With other contract based permissions I can add a revert and interrogate that. The permissioning contracts provide neither, happy to be corrected here...

**Comment by MadelineMurray** [comment]
@magooster - we talked about this today and wondered if you could expand on this point specifically: 
> With other contract based permissions I can add a revert and interrogate that.  

By _other contract based permissions_ do you mean contract permissioning implemented by another client? Or using Besu with an alternative permissioning contract? 

I'm going to update the Besu documentation to make this clearer but the provided [permissioning contracts](https://github.com/PegaSysEng/permissioning-smart-contracts) are a simple implementation and the Besu permissioning is designed so the contracts can be switched out for contracts designed to meet specific use cases.

**Comment by magooster** [comment]
I meant that a permissioning system can be added to any smart contract implementation, which is evaluated at transaction execution time within the EVM. I can then use a revert statement in my contract implementation to indicate a permissioning issue. The revert reason is available for clients for interrogation.  I can even invoke via a call to check prior to transaction submission.   This is not possible with the permissioning contract implementation as they are evaluated separately as part of the general transaction validation (gas price, gas supplied, signature etc).

**Comment by lucassaldanha** [comment]
> which is evaluated at transaction execution time within the EVM

I believe a problem with this approach is that the target node will need to allocate resources and start the tx execution in the EVM for any transactions, even those that aren't allowed. We have tried to avoid that with our implementation, applying permissioning rules outside the tx execution.

Even with onchain permisioning, the rules are written onchain, but the enforcement happens pre tx-execution. The spec even has specific events to allow caching of the allowed accounts s owe minimise the impact of evaluating the rules in the client.

> a permissioning system can be added to any smart contract implementation

This is correct. There are use cases that can benefit from this approach instead of the "EEA" approach. But then it isn't a client implementation domain and more a "smart contract domain", isn't it?

**Comment by macfarla** [comment]
@magooster we decided to change this to make Besu play nicer with MetaMask.  So this should work better for you now. https://github.com/hyperledger/besu/pull/2595 - let us know if this does/doesn't improve things for you!!
