### ISSUE TITLE
Expose the revert reason in the GraphQL receipt

### ISSUE THREAD

**Issue by roderik** [hyperledger/besu#1273]
### Description

Revert reasons can be exposed via the JSON RPC interface according to https://besu.hyperledger.org/en/stable/HowTo/Send-Transactions/Revert-Reason/

But they are not exposed int he GraphQL interface

### Acceptance Criteria
* Expose the revert reason in the schema when Besu is started with the parameter.

**Comment by catcs** [comment]
Taking a look! 👀

**Comment by catcs** [comment]
The jsonrpc API flow makes the revert reason very clear in the response definition (for example, see `org.hyperledger.besu.ethereum.api.jsonrpc.internal.results.TransactionReceiptResult` for the `eth_getTransactionReceipt` API function). The GraphQL API is fundamentally structured differently since GraphQL is more like a query language specification for APIs. It doesn't return a transaction receipt as such, but the GraphQL schema does define a `Transaction` (see `ethereum.api.src.main.resources.schema.graphqls`). The `Transaction` type includes a field for `status`, which will return `0` if a transaction failed (for example if it was reverted). That might be the best place to return the revert reason (more specifically, `org.hyperledger.besu.ethereum.api.graphql.internal.pojoadapter.TransactionAdapter.getStatus`). But since the revert reason is supposed to be an optional return value, I'm not sure the best way to configure that to be optional in the GraphQL API.

If someone with some more GraphQL experience has any ideas here let me know! Unassigning this issue from me for now in case someone else knows a solution.

**Comment by catcs** [comment]
This merged PR might also be helpful: https://github.com/hyperledger/besu/pull/2490/files

**Comment by macfarla** [comment]
@irenejoeunpark how about this one to start with?

**Comment by pullurib** [comment]
I'm working on this , please assign it to me. Looking into adding a revertReason field to graphQL schema in Transaction type dynamically depending on the --revert-reason-enabled option . This would be populated on transaction failure .

**Comment by matthew1001** [comment]
I've just assigned it to you
