### ISSUE TITLE
Run Benchmarks for EIP-2046 & 2666

### ISSUE THREAD

**Issue by timbeiko** [hyperledger/besu#1284]
On this week's AllCoreDevs, the benchmarks for EIP-2046 and EIP-2666 were brought up again. We should run them, and share our numbers with Alex Vlasov (@shamatar, not PegaSys' Alex Vlasov :-)).

**Comment by shamatar** [comment]
Would it be possible to get some data before this week ACD call?

**Comment by timbeiko** [comment]
@shamatar where are the other published results for EIP2666 repricing? We want to make sure we're doing an apples to apples benchmark. Thanks!

**Comment by shamatar** [comment]
@timbeiko 

There is a public spreadsheet [here](https://docs.google.com/spreadsheets/d/1aCQnk7prrp3Mbcf011BE5zZnkbc3Iw7QAixn6mLbKS0/edit?usp=sharing). When converting execution time to the gas I use a constant 35MGas/second.

**Comment by shamatar** [comment]
On the benchmarking side:
- hash functions (both SHA256/Ripemd160 called via precompiles, and Keccak being a VM function) get random bytestrings of fixed length as inputs
- BNAdd just gets two random points
- BNMul gets `2^256 - 1` as a scalar and random point
- BN pairing should get `N` pairs of random G1+G2 points, but since no repricing is proposed I was lazy to put the results there

There is NO intermediate glue (from EVM side). Function are pure like `function(bytes) -> bytes` and only this execution time is measured.

**Comment by shemnon** [comment]
Was there a specific machine these are run on?  t3.micro?  MacBook Pro 201x?

**Comment by shamatar** [comment]
It’s 2.9 GHz MBP 2018 (or may be 2.6, can check again tomorrow), but performance of a concrete machine is captured by the conversion constant. I've measured it based on ecrecover and BNMUL performance on my machine with turbo boost being off (assuming these two precompiles are well priced)

**Comment by shemnon** [comment]
My benchmark code - https://github.com/shemnon/besu/pull/3
A run in my 2018 Macbook Pro (2.6 GhZ i7) - https://gist.github.com/shemnon/0ddba91be501fa23291bdec9107fe99a

SHA256 is a Java built in
Keccak and RipeMD are pure java, and hence slower.  A native impl will be faster for both of these two and hopefully we will get bounties out this year for those two.
AltBN are native Rust code (borrowed from SputnikVM).  I'm not sure why the mul is so far off, there's probably room to optimize there.
