### ISSUE TITLE
Order Transactions By Gas Price and then By Time Added To Pool

### ISSUE THREAD

**Issue by RatanRSur** [hyperledger/besu#1285]
To prevent transaction spamming, most clients are implementing a FIFO ordering among transactions with the same gas price. From the code below, it looks like we already do that. However, it seems like we don't order by gas price, which is a problem for maximizing mining profits.

https://github.com/hyperledger/besu/blob/7b9ade23cde145e67f90112d3411e80f860129f6/ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/PendingTransactions.java#L72-L76

### Acceptance Criteria
Ensure that we order by gas price and then by time. If we don't do either, implement and test.

**Comment by MadelineMurray** [comment]
@RatanRSur - the current doc on the transaction pool talks about the order in which transactions are dropped - https://besu.hyperledger.org/en/stable/Concepts/Transactions/Transaction-Pool/#dropping-transactions-when-the-transaction-pool-is-full 

If there's updates needed to the doc when this issue is addressed, could you please ping Pliny.

**Comment by JoshMelton** [comment]
https://github.com/hyperledger/besu/pull/1314/files
I saw the issue when browsing, and decided to attempt to fix it, I think I am close, but I never actually was able to get anything running locally. 

I hope this helps some!
