### ISSUE TITLE
add cli flag for --static-nodes-file

### ISSUE THREAD

**Issue by mFarghaly** [hyperledger/besu#1414]
### Description
The only way to inject static nodes is to add static-nodes.json inside the data directory which makes it very hard  to automate in environments like Kubernetes 

### required feature

`besu --static-nodes-file /some/dir/static-nodes.json`

**Comment by terrencecooke** [comment]
Hi there, I would like to have this issue assigned to me.

**Comment by timbeiko** [comment]
@terrencecooke it's assigned to you now 😄 !

**Comment by mFarghaly** [comment]
This will simplify things in kotal.co 
thanks @terrencecooke

**Comment by terrencecooke** [comment]
Thanks!

**Comment by terrencecooke** [comment]
Would like to get a second (3rd, 4th, ... ) opinion.
After the changes I've made, this is how it currently works:

Situation 1:
When --static-nodes-file option is specified, besu chooses the SPECIFIED file, even if there is a static-nodes.json file in the data / default directory.

Situation 2:
When this is option is specified and the JSON file is ill-formed, besu will NOT continue the launch and will return an error.

Situation 3:
When this option is specified and the file isn't found (wrong path specified, a typo, just not there, etc), besu will simply display INFO message stating the file does not exist, and it will continue loading without connecting to static nodes. It will NOT consequently look for the default static-nodes.json file.

What do you think?
Does this operation make sense to the user?
Do you think most users would expect this to work in a different way?
I'm open to opinions.

**Comment by terrencecooke** [comment]
On second thought, the aforementioned situations I mentioned, collectively seem pretty consistent with the way it already works with static-nodes.json file.  It fails only when the file chosen is ill-formed, and continues loading without connecting to static nodes, if the file is not found.

I do think situation 3 is clear as is.  At first I was thinking that if the file specified on the option line wasn't found, that it should then search for the default static-nodes.json in the default / data directory. However, it's probably better to NOT connect to static nodes at all, rather than to connect to a list of static nodes inadvertently.

**Comment by mFarghaly** [comment]
currently static nodes are read from a single location data-dir/static-nodes
instead of reading from this single/fixed location, accept it as cli flag and/or env var
that's it, I think the rest of the scenarios are already taken care of.

**Comment by terrencecooke** [comment]
Great! Thanks!

**Comment by terrencecooke** [comment]
PR 1644 is available
