### ISSUE TITLE
EIP-1898

### ISSUE THREAD

**Issue by wetryingtodorock** [hyperledger/besu#1733]
Hello! Can you tell me, please, do you have this option? https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1898.md
If no, then when do you plan to implement it?

**Comment by timbeiko** [comment]
I don't think we support this, no, but it should be a pretty straightforward thing to add. Is your use case simply querying blocks by hashes rather than number, @wetryingtodorock? Thanks!

**Comment by wetryingtodorock** [comment]
Yes, EIP says about this, it’s needed to add the option that will allow getting the data by hash for some methods.

Our clients are asking about the support for EIP. As we understood, currently it supports only Geth 1.9.6 and higher versions. If this EIP is accepted by the community, maybe it would be better to implement it to Besu as well.

Thanks.

**Comment by Chainode** [comment]
Adding the EIP 1898 to the Besu client will make it very strong. Querying blocks by hashes rather than number helps a lot to make sure the data is consistent and would also make the client compatible with protocols like The Graph which is used for indexing subgraphs data from Ethereum Archive nodes.
