### ISSUE TITLE
Make PrivacyReorgTest Not Depend on Hardcoded State Roots

### ISSUE THREAD

**Issue by RatanRSur** [hyperledger/besu#1793]
The `PrivacyReorgTest` is brittle with respect to anything that changes where in `BlockDataGenerator`'s random stream it gets its values from.

### Acceptance Criteria
* It determines what should be the correct state roots at test time or otherwise tests the properties so that the changes to the random stream don't affect it.

**Comment by frankisawesome** [comment]
Bit stuck on this one, how did we get these hard coded state roots and is it possible to generate them in BlockDataGenerator? @RatanRSur any pointers?

**Comment by RatanRSur** [comment]
@frankisawesome Hey! The hardcoded state roots were probably from when someone ran the test without knowing what the state roots would be and pulled them out of whatever was generated at the time to make the assertion pass.

All the state roots you see are already generated from `BlockDataGenerator`.

What you want to do is more directly encode the intention "make sure this block I just generated is in the given position after this reorg" without referring to it by state root (which can change).

**Comment by frankisawesome** [comment]
So a couple of more things that need to change here - all the state root assertions need to go and we'll need to assert the block's actual properties rather than the state root? @RatanRSur

**Comment by frankisawesome** [comment]
- note find the public chain equivalent and see how that's implemented

**Comment by frankisawesome** [comment]
No luck on this one so I'm unassigning myself.

My final thoughts were: rather than mining the blocks in block data generator which is not something we want to do, we can simply get the block processors to not validate the public state roots since the tests shouldn't care about the public state roots and we're only asserting the private state roots stay the same after reorg.

However the way we construct the validators means it's very difficult to mock them, not sure if possible at all. Dropping this one and happy to have a chat with the next person who picks it up :)
