### ISSUE TITLE
Migration script testing 

### ISSUE THREAD

**Issue by MadelineMurray** [hyperledger/besu#1953]
`see it work` testing for Orion -> Tessera migration script. Similar to @pinges's privacy on a forking consensus mechanism test. 

- [x] Create Besu <> Orion network and submit a number of transactions 
- [x] Migrate Orion -> Tessera 
- [x] Restart network with Besu <> Tessera and confirm private group states match

**Comment by macfarla** [comment]
Besu > Orion

**Comment by macfarla** [comment]
```
{
    "jsonrpc": "2.0",
    "method": "priv_debugGetStateRoot",
    "params": [
        "MC4aHjApHsGb0j5glU2iAj5KcR5LId52S0BU9mtdeuY=",
        "latest"
    ],
    "id": 1
}
```

>
```
 {
    "jsonrpc": "2.0",
    "id": 1,
    "result": "0x69904cc3945ada15579fa6f7f1c95e31555210ac017646b4a1373412281dce82"
}
```

**Comment by macfarla** [comment]
"keys" : {
      "keyData" : {
         "privateKeyPath" : "/Users/sallymacfarlane/workspace/tessera/migration/orion-to-tessera/workdir/orion1/keys/orion.key",
         "publicKeyPath" : "/Users/sallymacfarlane/workspace/tessera/migration/orion-to-tessera/workdir/orion1/keys/orion.pub"
      }
   },

**Comment by macfarla** [comment]
tessera config gets this:

```
{
   "type" : "config",
   "version" : "20.10.2-SNAPSHOT",
   "useWhiteList" : false,
   "disablePeerDiscovery" : false,
   "bootstrapNode" : false,
   "jdbc" : {
      "username" : "sa",
      "password" : "sa",
      "url" : "jdbc:h2:./target/h2/tessera-88",
      "autoCreateTables" : true,
      "fetchSize" : 0
   },
   "serverConfigs" : [ {
      "app" : "Q2T",
      "communicationType" : "REST",
      "serverAddress" : "http://127.0.0.1:8081/",
      "properties" : {
      }
   }, {
      "app" : "P2P",
      "communicationType" : "REST",
      "serverAddress" : "http://127.0.0.1:8081/",
      "properties" : {
      }
   } ],
   "peer" : [ {
      "url" : "http://127.0.0.1:8081"
   }, {
      "url" : "http://127.0.0.1:8082"
   }, {
      "url" : "http://127.0.0.1:8083"
   } ],
   "keys" : {
      "keyData" : {
         "privateKeyPath" : "/Users/sallymacfarlane/workspace/tessera/migration/orion-to-tessera/workdir/orion1/keys/orion.key",
         "publicKeyPath" : "/Users/sallymacfarlane/workspace/tessera/migration/orion-to-tessera/workdir/orion1/keys/orion.pub"
      }
   },
   "alwaysSendTo" : [ ],
   "features" : {
      "enableRemoteKeyValidation" : false,
      "enablePrivacyEnhancements" : false
   },
   "encryptor" : {
      "type" : "NACL"
   },
   "mode" : "orion"
}
```

**Comment by macfarla** [comment]
so then running Tessera with that config (fixing the Q2T port to 8881)
```
{
    "jsonrpc": "2.0",
    "method": "priv_findPrivacyGroup",
    "params": [
        [
            "GGilEkXLaQ9yhhtbpBT03Me9iYa7U/mWXxrJhnbl1XY="
        ]
    ],
    "id": 1
}
```
gives no results
```
{
    "jsonrpc": "2.0",
    "id": 1,
    "result": []
}
```

**Comment by macfarla** [comment]
{
    "jsonrpc": "2.0",
    "id": 1,
    "result": "0x23b483b707dd23c2798004d689aa958cbdc1f9069a48621b6ad500cb27960217"
}

**Comment by macfarla** [comment]
With latest migration branch, with the fix for privacy groups. 
```
*   13183b76c (HEAD -> orion-migration-tool) Merge branch 'orion-migration-tool' of github.com:ConsenSys/tessera into orion-migration-tool
|\
| * ae48f5b88 (upstream/orion-migration-tool) passwords file is also in workdir.
| * 7ea425729 read in wrong value for privacy group id as in orion db key is in base64 format
* | 3d539bad3 Merge branch 'orion-migration-tool' of github.com:ConsenSys/tessera into orion-migration-tool
|\|
```

Tested with various combinations of batches of transactions, and then using priv_debugGetStateRoot to test that states are equal
https://docs.google.com/spreadsheets/d/1Ty88ok9YqKhSNRWGhiM32v7mKd-tEeda7Gtj1qI5Xq0/edit#gid=0 
Also tested migrating a db that is set up for multi-tenancy. 
Tested running this script to create privacy groups directly, and after migrating the result is the same: web3js-eea/example/multiTenancy/createPrivacyGroupMultiTenancy.js

**Comment by MadelineMurray** [comment]
@macfarla - to add sample command line to run migration.

**Comment by MadelineMurray** [comment]
Have tested with LevelDB only at this point. Use priv_debugGetStateRoot to check has worked correctly.

**Comment by macfarla** [comment]
How to run it
1. Build the migration tool. 
First, the code is currently on a branch so you have to check that out and build it
https://github.com/ConsenSys/tessera/pull/1246

2. Start Orion. 
Then run up Besu & Orion - I've been using this setup https://github.com/lucassaldanha/besu-local-nodes but if you already have your own that's also fine. 
```
cd ~/workspace/besu-local-nodes
besu --config-file config/besu/besu1.conf
orion config/orion/orion1.conf
```

3. Send some txs
Then create some txs - I've been using web3js-eea examples as described above. The concurrentPrivateTxs example only needs one Orion node running, the multiNode ones generally need 2 or 3.
If you're going to use priv_debugGetStateRoot (and priv_getTransactionCount is also useful) to test before & after, you can run this against your privacy groups now while Orion is running. eg use concurrentPrivateTxs.js to send 50 txs to orion1 and 40 txs to orion 2&3
Note to use web3js-eea examples you need to make sure the keys.js match your environment - the keys for all besu/orion nodes are in the readme for the besu-local-nodes repo if you're using that setup.
To do this you change these lines in the js 
```
const TX_COUNT = 50; # change this number to send a different number of txs
const BATCH_SIZE = 5;

// options used to create a privacy group with only one member
const privacyOptions = {
  privateFrom: orion.node1.publicKey,
  privateFor: [orion.node1.publicKey], ## change this to send to different recipients eg [orion.node2.publicKey,orion.node3.publicKey]
  privateKey: besu.node1.privateKey
};
```

4. Stop Orion.
Then stop Besu & Orion.

5. Run the migrate
Then you run the migrate - and it does everything relative to the current directory so to make my life easier I've been running it from ~/workspace/besu-local-nodes where I have this repo checked out - it has orion config ready to go - https://github.com/lucassaldanha/besu-local-nodes
to see the help:
`~/workspace/tessera/migration/orion-to-tessera/build/install/migrate/bin/migrate --help` 
example command line:
`~/workspace/tessera/migration/orion-to-tessera/build/install/migrate/bin/migrate -f ~/workspace/besu-local-nodes/config/orion/orion1.conf -o tessera-migrated.conf tessera.jdbc.user sa tessera.jdbc.password sa tessera.jdbc.url jdbc:h2:./workdir/orion1/tessera1`
it will create tessera-migrated.conf and ./workdir/orion1/tessera1 db (change these arguments if you want them to go somewhere different)

6. Run Besu&Tessera
I have it aliased so wherever you have tessera checked out to - mine is /Users/sallymacfarlane/workspace/tessera/
`alias tessera=java\ -jar\ /Users/sallymacfarlane/workspace/tessera/tessera-dist/tessera-app/target/tessera-app-21.1.1-SNAPSHOT-app.jar`
or you can just run `java jar path-to-tessera.jar -configfile tessera-migrated.conf`
Note the config file created by the migration script has the mode=orion in it so you don't need to specify on the cmd line. And nothing needs to change in besu.
Again I'm running this from ~/workspace/besu-local-nodes because all paths (eg in tessera-migrated.conf) are relative from there.
```
tessera -configfile tessera-migrated.conf
besu --config-file config/besu/besu1.conf
```
7. Verify the state
use priv_debugGetStateRoot and priv_getTransactionCount

8. Send more txs
Verify that you can send further txs - again using web3js-eea examples or your preferred method.

9. Stop Tessera
Once you're done, stop Besu & Tessera

**Comment by macfarla** [comment]
New things: 
1. if you point the migration at an existing tessera db, it will throw an exception if the tables are non-empty - this allows DBAs to create the db in advance of the migration but prevents mixing up unrelated data
2. password-protected keys are now converted as part of the migration (although there is a bug where the filename is incorrect in the config file - but this should be easy to fix)

**Comment by macfarla** [comment]
password protected keys get migrated successfully but in the process the orion keys get renamed to .orion and the filename is used for the tessera format - so the tessera config points to the same filename as the orion config did. Which is only a problem if you need to redo the migration... you will need to reinstate the original orion keys first

**Comment by macfarla** [comment]
blocked on testing the TLS piece

**Comment by macfarla** [comment]
```
{
    "jsonrpc": "2.0",
    "method": "priv_getTransactionCount",
    "params": [
        "0xfe3b557e8fb62b89f4916b721be55ceb828dbd73",
        "67NmE7/94nuomQiZv/g19BzyhhX84kwJo3lr5+n43xI="
    ],
    "id": 1
}
```
result
```
{
    "jsonrpc": "2.0",
    "id": 1,
    "result": "0xb4"
}
```
