### ISSUE TITLE
Test Besu -> Tessera TLS configuration

### ISSUE THREAD

**Issue by mark-terry** [hyperledger/besu#2045]
### Description
The Besu -> Tessera configuration needs to be verified and tested.

### Acceptance Criteria
Verify that the TLS connection works as expected.
- [x] Tessera <> Tessera
- [x] Tessera <> Besu
- [x] instructions for how to generate certs for Tessera to use

**Comment by macfarla** [comment]
TLS - Generating certificates - Do you have instructions for how to generate certs for Tessera? eg here we have instructions for Orion generating certs - https://docs.orion.consensys.net/en/stable/Tutorials/Generating-Certificates/

Tessera team says:
These are instructions to generate any certificate - Tessera should be able to use them. I don’t think anything special need to be done although if running on localhost it’s likely you also need to include the port in the CN.
But let me try this and get back to you

**Comment by macfarla** [comment]
```
       {
           "app":"P2P",
           "serverAddress":"https://localhost:8081",
           "sslConfig": {
               "tls" : "STRICT",
               "generateKeyStoreIfNotExisted" : "true",
               "serverTlsKeyPath" : "/Users/sallymacfarlane/workspace/besu-local-nodes/key.pem",
               "serverTlsCertificatePath" : "/Users/sallymacfarlane/workspace/besu-local-nodes/cert.pem",
               "serverTrustMode" : "TOFU",
               "clientTlsKeyPath" : "/Users/sallymacfarlane/workspace/besu-local-nodes/key.pem",
               "clientTlsCertificatePath" : "/Users/sallymacfarlane/workspace/besu-local-nodes/cert.pem",
               "clientTrustMode" : "TOFU",
               "knownClientsFile" : "/Users/sallymacfarlane/workspace/besu-local-nodes/knownClients",
               "knownServersFile" : "/Users/sallymacfarlane/workspace/besu-local-nodes/knownServers"
           },
           "communicationType" : "REST"
       }
```

When I use cert.pem and key.pem from tessera/security/src/test/resources/ the above config runs ok, and 2 tessera nodes can communicate using SSL. However if I run with the certs generated by orion I get an error
2021-03-22 11:29:29.849 [pool-3-thread-1] WARN  c.q.t.p.p.PartyInfoBroadcaster - Failed to connect to node https://localhost:9002/, due to javax.net.ssl.SSLHandshakeException: No name matching localhost found
and if I replace localhost with 127.0.0.1 in the config I get this error:
2021-03-22 11:20:52.312 [pool-3-thread-1] WARN  c.q.t.p.p.PartyInfoBroadcaster - Failed to connect to node https://127.0.0.1:9002/, due to javax.net.ssl.SSLHandshakeException: No subject alternative names present

**Comment by macfarla** [comment]
From Tessera team:
The issue is Orion automatically generate the certificate with something like 127.0.0.1:8080 in the CN field of the certificate. When it comes to IP address Java is stricter that it enforces the certificate contains a SAN (Subject Alternative Names) entry for the IP as having the url in the CN has become obsolete.
so - 2 ways you can get it working
Follow the Orion instruction to generate certs here https://docs.orion.consensys.net/en/stable/Tutorials/Generating-Certificates/#public-dns-is-cn and ensure that the CN=localhost
Follow instruction to generate certs https://docs.orion.consensys.net/en/stable/Tutorials/Generating-Certificates/#ip-address-is-cn and have the SAN configured to include 127.0.0.1
and Tessera should be able to start with those certificates

**Comment by macfarla** [comment]
I followed the instructions as suggested (I tried both ways, and orion can run with the certs generated) but Tessera gives this error:
com.quorum.tessera.ssl.exception.TesseraSecurityException: java.security.spec.InvalidKeySpecException: java.security.InvalidKeyException: IOException : algid parse error, not a sequence
	at com.quorum.tessera.ssl.context.ServerSSLContextFactoryImpl.from(ServerSSLContextFactoryImpl.java:49)
	at com.jpmorgan.quorum.server.utils.ServerUtils.buildWebServer(ServerUtils.java:44)
	at com.quorum.tessera.server.JerseyServer.start(JerseyServer.java:88)
	at com.quorum.tessera.launcher.Launcher$1.launchServer(Launcher.java:58)
	at com.quorum.tessera.launcher.Main.main(Main.java:88)
Caused by: java.security.spec.InvalidKeySpecException:

**Comment by macfarla** [comment]
need to verify whether we can use PKCS1 key or does it need to be converted to PKCS8

**Comment by macfarla** [comment]
confirming the PKCS1 key works (as generated by instructions in Orion docs) https://docs.orion.consensys.net/en/latest/Tutorials/Generating-Certificates/

PKCS1 key: 
```
               "serverTlsKeyPath" : "/Users/sallymacfarlane/workspace/besu-local-nodes/orion_cer2.key",
               "serverTlsCertificatePath" : "/Users/sallymacfarlane/workspace/besu-local-nodes/orion_cer2.pem",
```
PKCS8 key generated by
`openssl pkcs8 -topk8 -inform PEM -outform PEM -nocrypt -in orion_cer2.key -out pkcs8-2.key`
```
               "serverTlsKeyPath" : "/Users/sallymacfarlane/workspace/besu-local-nodes/pkcs8-2.key",
               "serverTlsCertificatePath" : "/Users/sallymacfarlane/workspace/besu-local-nodes/orion_cer2.pem",
```

**Comment by macfarla** [comment]
A couple of things to make clear in the docs for 

1.  If running on localhost, you can follow the instructions for generating certs in Orion docs. You just need to make sure that the certificates are generated with "localhost" in the CN (ie when you answer the questions, make sure you specify localhost as CN) eg:
```
$ openssl x509 -in orion_cer.pem -text -noout
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number: 14652134239262280134 (0xcb56d675d49109c6)
    Signature Algorithm: sha256WithRSAEncryption
        Issuer: C=AU, ST=QLD, L=Brisbane, O=ConsenSys, CN=localhost
        Validity
            Not Before: Apr  1 01:49:10 2021 GMT
            Not After : Aug 14 01:49:10 2022 GMT
        Subject: C=AU, ST=QLD, L=Brisbane, O=ConsenSys, CN=localhost
```
The issue is Orion automatically generate the certificate with something like 127.0.0.1:8080 in the CN field of the certificate. When it comes to IP address Java is stricter that it enforces the certificate contains a SAN (Subject Alternative Names) entry for the IP as having the url in the CN has become obsolete.
so - 2 ways you can get it working
Follow the Orion instruction to generate certs here https://docs.orion.consensys.net/en/stable/Tutorials/Generating-Certificates/#public-dns-is-cn and ensure that the CN=localhost
Follow instruction to generate certs https://docs.orion.consensys.net/en/stable/Tutorials/Generating-Certificates/#ip-address-is-cn and have the SAN configured to include 127.0.0.1
and Tessera should be able to start with those certificates

2. If running multiple tessera/besu nodes on a single host - Use separate knownClients and knownServers for P2P and Q2T endpoints in Tessera config. eg
```
   "serverConfigs":[
       {
           "app":"ThirdParty",
           "serverAddress": "http://localhost:8581",
           "communicationType" : "REST"
       },
       {
           "app":"Q2T",
           "serverAddress":"https://localhost:8881",
           "sslConfig": {
               "tls" : "STRICT",
               "generateKeyStoreIfNotExisted" : "true",
               "serverTlsKeyPath" : "/Users/sallymacfarlane/workspace/besu-local-nodes/orion_cer1.key",
               "serverTlsCertificatePath" : "/Users/sallymacfarlane/workspace/besu-local-nodes/orion_cer1.pem",
               "serverTrustMode" : "TOFU",
               "clientTlsKeyPath" : "/Users/sallymacfarlane/workspace/besu-local-nodes/orion_cer1.key",
               "clientTlsCertificatePath" : "/Users/sallymacfarlane/workspace/besu-local-nodes/orion_cer1.pem",
               "clientTrustMode" : "TOFU",
               "clientAuth" : "false",
               "knownClientsFile" : "/Users/sallymacfarlane/workspace/besu-local-nodes/knownClients1",
               "knownServersFile" : "/Users/sallymacfarlane/workspace/besu-local-nodes/knownServers1"
           },
           "communicationType" : "REST"

       },
       {
           "app":"P2P",
           "serverAddress":"https://localhost:8081",
           "sslConfig": {
               "tls" : "STRICT",
               "generateKeyStoreIfNotExisted" : "true",
               "serverTlsKeyPath" : "/Users/sallymacfarlane/workspace/besu-local-nodes/orion_cer1.key",
               "serverTlsCertificatePath" : "/Users/sallymacfarlane/workspace/besu-local-nodes/orion_cer1.pem",
               "serverTrustMode" : "TOFU",
               "clientTlsKeyPath" : "/Users/sallymacfarlane/workspace/besu-local-nodes/orion_cer1.key",
               "clientTlsCertificatePath" : "/Users/sallymacfarlane/workspace/besu-local-nodes/orion_cer1.pem",
               "clientTrustMode" : "TOFU",
               "knownClientsFile" : "/Users/sallymacfarlane/workspace/besu-local-nodes/knownClients3",
               "knownServersFile" : "/Users/sallymacfarlane/workspace/besu-local-nodes/knownServers3"
           },
           "communicationType" : "REST"
       }
   ],
```
