### ISSUE TITLE
Build Failure - Task :checkSpdxHeader FAILED

### ISSUE THREAD

**Issue by theyashl** [hyperledger/besu#2450]
### Description
As an Developer, I want to be able to build master without any errors. 

### Steps to Reproduce (Bug)
1. Install Besu using `git clone --recursive https://github.com/hyperledger/besu`
2. `cd besu`
3. run `.\gradlew build -x test`

**Expected behavior:** Should be able to complete the build without any errors.

**Actual behavior:** Build is failing with the following error :
 Task :checkSpdxHeader FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':checkSpdxHeader'.
> Files without headers: D:\Research\BesuN\besu\ethereum\api\build\generated\sources\annotationProcessor\java\main\org\hyperledger\besu\ethereum\api\ImmutableApiConfiguration.java
+ There is a very long list of files below this. I just attached one. And all of them have same parent directory. i.e. ethereum.

**Frequency:** Every time I tried to run the build command

### Versions (Add all that apply)
* Software version: 21.1.7
* Java version: 13.0.2
* OS Name & Version: Windows 10 Home Single Language v21H1

### Additional Information

BUILD FAILED in 4m 45s
84 actionable tasks: 84 executed

**Comment by vmichalik** [comment]
Hey @theyashl, thanks for raising an issue! looking into this for you

**Comment by vmichalik** [comment]
Hi @theyashl sorry for the delay here.

@matkt thinks it's related to Windows because of the path we exclude:
https://github.com/hyperledger/besu/blob/a75301b6a97f01c7d3480f293e32bbb0d1250c70/build.gradle#L748

Maybe because in Windows it's \build\  and not /build/

Generally we advise people to build on Linux where possible for the best developer experience. Further docs are here. https://wiki.hyperledger.org/display/BESU/Building+from+source

**Comment by theyashl** [comment]
Thank you for your response @vmichalik . I can totally understand the problem as you mentioned.
So I'll just try to build besu on WSL on Windows.
