### ISSUE TITLE
Change behavior of tx replacement price bump requirements

### ISSUE THREAD

**Issue by RatanRSur** [hyperledger/besu#2529]
Right now we require a percentage increase on the effective priority fee per gas. This causes undesirable properties because most txs stuck in the pool and eligible for replacement will have an effective priority fee per gas of 0. That means that the price bump will be 0. We should require a bump of both the feeCap and maxPriorityFeePerGas.

**Comment by garyschulte** [comment]
What I see in TransactionReplacementByPriceRule is that we replace if the *effective price* of the transaction is above a threshold percentage of the existing transaction, not the effectivePriorityFee.

It seems to me the correct behavior here is subjective.
* if the miner were 100% altruistic, they would:
  * always want to replace a transaction with one with a higher effective price

* if the miner were 100% selfish, they would:
  * always want to replace a transaction with one with a higher effective priority fee
  * only want to replace with a similar effective priority fee is the same if the effective price is higher since it has a higher likelihood of executing
  * never replace an existing transaction with one with a lower effective priority fee

That last point is not 100% certain.  A selfish miner might want to replace a transaction with one with a lower effective priority fee IF there was a better chance it would execute and net some revenue versus no revenue.
