### ISSUE TITLE
ether value is not supported for private transactions

### ISSUE THREAD

**Issue by ehanoc** [hyperledger/besu#2606]
### Description
Updating to **21.7.1** currently all mainnet transactions fail with ``` ether value is not supported for private transactions ```
Transaction signature (r,s,v) with v == 37 or v == 38 

According to https://eips.ethereum.org/EIPS/eip-155; (replay protection)

chain_id == 1 ; v should be either 37 or 38. Minimum. 

But in here https://github.com/hyperledger/besu/blob/992c6563870ea87874e80b93d3dc6ce93dce880f/ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/Transaction.java#L629

V = 37 & v = 38; should still be valid with mainnet txs unless if including the private txs fields such as privateFor, privateFrom, privacyGroupId, etc... 

What am i missing?

Note: With previous version **21.1.7** works fine

**Comment by pedrobranco** [comment]
This is affecting Ethereum mainnet transactions (with v = 37/38), and since we're close to the London fork, do we have any ETA to solve this issue (if confirmed)?

**Comment by garyschulte** [comment]
Can you provide more detail on how you are sending the transactions?  Are you not able to provide the chain id in the transactions?

**Comment by lucassaldanha** [comment]
Thank you for raising this ticket. I can confirm that we have identified an issue with the misclassification of public transactions as private transactions.

## The Problem

The scope of this problem is limited to:
- Value transfer public transactions received via JSON-RPC
- Value transfer public transactions received via DevP2P

When receiving a value transfer tx via JSON-RPC, Besu was considering it a private tx and enforcing a validity check that prevents private transactions from transferring value. That's why it was returning the error message `ether value is not supported for private transactions`.

When receiving value transfer tx via DevP2P, Besu was considering those transactions invalid, not propagating them further.

Luckily, the logic for block validation and import wasn't using the same code path. This means that Besu would still successfully synchronise with Mainnet and be up-to-date. **This bug won't cause a fork**.

We have already merged the fix for this issue and we will release version `21.7.2` in a few hours. Even though this bug won't impact London chain synchronization and won't cause forks, we recommend that all users update their Besu versions its latest version.

## Actions

To prevent something like this from happening again, we have added a test that validates that transactions with `chainId = 1 ` (and any other chainId) won't be affected by private transaction logic.

A hotfix version `21.7.2` will be released containing the fix.

## Next Steps

We will review the branching of execution of public v private transactions in an effort to better isolate their differences. The ideal scenario would be that, when running on public networks, none of the private tx logic would be ever in the code execution path.
