### ISSUE TITLE
Private Transaction Failed when invoke a Public Contract with 2 Indirections

### ISSUE THREAD

**Issue by albert0-hernandez** [hyperledger/besu#2803]
### Description
As an besu developer
I want to deploy a private contract which read from public state with two inderections
so my logic executed correctly according to private state read/write rules.

### Acceptance Criteria
* The lastes version of Besu behaves in the similar way to Besu v21.1.5 versions

### Steps to Reproduce (Bug)
1. Clone the Repository https://github.com/albert0-hernandez/private-to-public-besu-tester.git
2. Follow the Readme steps to install, run & test
3. See that the test labelled as 2.c. failed

**Expected behavior:** 
With Besu versions up to 21.1.5 the test will succeeded with no problem.

1. Clone the Repository https://github.com/albert0-hernandez/private-to-public-besu-tester.git
2. Modify the base version of Besu from 21.7.4 to 21.1.5 on hyperledger-besu-tessera-network/config/templates/docker-compose-microservices.yaml
3. Follow the Readme steps to  run & test
3. See that the test labelled by 2.c. succeeded

**Actual behavior:** 
When you deploy a configuration of Smartcontracts that chain an execution like:
    Private SC (calls) -> Public SC (calls) -> Public SC 
The execution failed.

**Frequency:** 
100%

### Versions (Add all that apply)
* Software version: >= 21.1.6 
* Java version: Official Dockerized version
* OS Name & Version: Docker

### Additional Information
This behaviour is reproduced migrating a validated fully tested SC solution on 21.1.3 to 21.7.4.
We created a sample project to better (and simplified) behaviour that we observe after migrating.

**Comment by antonydenyer** [comment]
The bug is actually related to value transfer.

User → PrivateContract → PublicContract1 → PublicContract2

Interestingly when the PrivateContract is executed a mutable account is acquired for the PrivateContract then a mutable account is acquired for the PublicContract1 address but in the private world state! Consequently, this works because it is `getOrCreate`. Then when the PublicContract1 goes to call PublicContract2 it attempts to acquire a mutable account in the public world state which it is not allowed to do. An exception is thrown and the transaction is reverted.

Given that we are not transferring value from private to public state we can put some better guards in place so that the `MessageCallProcessor` does not need to acquire a mutable account.
