### ISSUE TITLE
Add support for other key algorithms for JWT auth

### ISSUE THREAD

**Issue by macfarla** [hyperledger/besu#2981]
Currently we assume the algo is RSA but there's no reason for this restriction. 
In theory, we can support whatever algorithms the JWT spec and Vertx can support. The JWT protocol allows for the use of much stronger algorithms that can be executed by virtually any major cryptographic library (OpenSSL, libgcrypt, NaCL, libsodium, Botan, etc.)

Will require a docs change since we specifically mention RSA: https://besu.hyperledger.org/en/stable/HowTo/Interact/APIs/Authentication/

**Comment by anipaul2** [comment]
Hey, I'm a new beginner. Can you suggest to me how to get started with this?

**Comment by macfarla** [comment]
@anipaul2 depends on what you mean by a new beginner :) This one will require knowledge of JWT and Vert.x - if you are still getting up to speed with more basic concepts then this one might not be the best to start on. We can find you something though, let us know!

**Comment by anipaul2** [comment]
please find me something that I can get started with.

**Comment by macfarla** [comment]
how about this one @anipaul2 `https://github.com/hyperledger/besu/issues/2756`

**Comment by frankisawesome** [comment]
Did some further research on this, came across this article https://auth0.com/blog/critical-vulnerabilities-in-json-web-token-libraries/

Seems like there have been past attacks taking advantage of the different signing algorithms.. Although that definitely seems to have been fixed since. 

The author seems to think the `alg` field on JWTs should be deprecated at a JWT standard level and backend applications should be passing the algorithm used to JWT libraries. (As far as I can tell this hasn't been adopted and there are definitely APIs out there that accept many signing algorithms)

Your thoughts @macfarla ?
