### ISSUE TITLE
`blockperiodseconds` in IBFT 2.0 falsely interpreted when set to value < 1 

### ISSUE THREAD

**Issue by arne-da** [hyperledger/besu#3088]
### Bug report
If `blockperiodseconds` is set to <1s, e.g. even '0.99' (instead of '1'), the block mining frequency is falsely becoming an extremely low value. I observe blocks being mined as frequent as every 5ms instead of the intended 999ms. 

### Why?
As a developer writing an application integrating with Besu that needs lower latency than the out-of-the-box options provide, I want to be able to set the block mining frequency with IBFT 2.0 to a number lower than 1s.  

### Steps to Reproduce (Bug)
1. Follow the steps of the [IBFT 2.0 quickstart tutorial](https://besu.hyperledger.org/en/21.10.2/Tutorials/Private-Network/Create-IBFT-Network/).
2. Do everything as suggested, except change the `blockperiodseconds` in `ibftConfigFile.json` from 
```
"blockperiodseconds": 2,
```
to 
```
"blockperiodseconds": 0.99,
```
3. Start the network

**Expected behavior:** A block mining frequency of 0.99 seconds. 

**Actual behavior:** 
Filtering the logs of `node1` for just 'New chain head detected ...' messages, I see blocks being mined extremely frequently: 
```
...
2021-11-19 13:44:01.262+01:00 | pool-8-thread-1 | DEBUG | BaseBftController | New chain head detected (block number=122), currently mining on top of 121.
│2021-11-19 13:44:01.276+01:00 | pool-8-thread-1 | DEBUG | BaseBftController | New chain head detected (block number=123), currently mining on top of 122.
│2021-11-19 13:44:01.293+01:00 | pool-8-thread-1 | DEBUG | BaseBftController | New chain head detected (block number=124), currently mining on top of 123.
│2021-11-19 13:44:01.307+01:00 | pool-8-thread-1 | DEBUG | BaseBftController | New chain head detected (block number=125), currently mining on top of 124.
│2021-11-19 13:44:01.324+01:00 | pool-8-thread-1 | DEBUG | BaseBftController | New chain head detected (block number=126), currently mining on top of 125.
│2021-11-19 13:44:01.341+01:00 | pool-8-thread-1 | DEBUG | BaseBftController | New chain head detected (block number=127), currently mining on top of 126.
│2021-11-19 13:44:01.359+01:00 | pool-8-thread-1 | DEBUG | BaseBftController | New chain head detected (block number=128), currently mining on top of 127.
│2021-11-19 13:44:01.374+01:00 | pool-8-thread-1 | DEBUG | BaseBftController | New chain head detected (block number=129), currently mining on top of 128.
│2021-11-19 13:44:01.387+01:00 | pool-8-thread-1 | DEBUG | BaseBftController | New chain head detected (block number=130), currently mining on top of 129.
│2021-11-19 13:44:01.400+01:00 | pool-8-thread-1 | DEBUG | BaseBftController | New chain head detected (block number=131), currently mining on top of 130.
│2021-11-19 13:44:01.413+01:00 | pool-8-thread-1 | DEBUG | BaseBftController | New chain head detected (block number=132), currently mining on top of 131.
│2021-11-19 13:44:01.422+01:00 | pool-8-thread-1 | DEBUG | BaseBftController | New chain head detected (block number=133), currently mining on top of 132.
│2021-11-19 13:44:01.435+01:00 | pool-8-thread-1 | DEBUG | BaseBftController | New chain head detected (block number=134), currently mining on top of 133.
│2021-11-19 13:44:01.449+01:00 | pool-8-thread-1 | DEBUG | BaseBftController | New chain head detected (block number=135), currently mining on top of 134.
│2021-11-19 13:44:01.462+01:00 | pool-8-thread-1 | DEBUG | BaseBftController | New chain head detected (block number=136), currently mining on top of 135.                                         
│2021-11-19 13:44:01.475+01:00 | pool-8-thread-1 | DEBUG | BaseBftController | New chain head detected (block number=137), currently mining on top of 136.
...
```
I observe the intended block mining frequency when changing `blockperiodseconds` from 0.99 to 1 in the genesis file. 

**Frequency:** Always

### Versions (Add all that apply)
* Software version: `besu/v21.10.2/linux-x86_64/openjdk-java-11`
* Java version: `openjdk 11.0.11 2021-04-20`
* OS Name & Version: Ubuntu 18.04 LTS
* Kernel Version: `Linux arne-Precision-5540 5.4.0-90-generic #101~18.04.1-Ubuntu SMP Fri Oct 22 09:25:04 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by siladu** [comment]
Hi, thanks for reporting this and apologies for the late reply. 
The reason you're experiencing this behaviour is because `blockperiodseconds` expects integer second values and in this instance 0.99 was getting rounded _down_ 0.
A `blockperiodseconds` of 0 results in blocks being constantly mined which will quickly fill up the disk space.

We have added some validation to make the expectation for this config clearer, i.e. only allow positive integers: https://github.com/hyperledger/besu/issues/3093

This has also caused some discussion in my team about whether we could or should support decimal block period values. The conclusion is that technically it could work but may require significant changes in how the block validation works. 
One concern is that the block timestamp only has second granularity so if anyone (e.g. a via smart contract) is relying on block timestamps for ordering, then sub-second block production may cause problems.

Despite it being feasible, this is not something we are planning to add to our roadmap at this stage. However, contributions are always welcome :)
