### ISSUE TITLE
SPIKE: add metrics for RocksDB

### ISSUE THREAD

**Issue by macfarla** [hyperledger/besu#3369]
Currently we have no metrics around RocksDB. Investigate what would be involved. What metrics make sense?
 - [ ] useful metrics
 - [ ] not detrimental to performance

**Comment by fab-10** [comment]
@macfarla it seems that RocksDB metrics are already collected, see `RocksDBMetricsFactory` for example, but I am not able to see them exposed by Prometheus, so there could be some issues on exposing these metrics.

**Comment by ajsutton** [comment]
That category may just be disabled by default.  From memory there were some categories disabled because they included timers I think which had a significant performance impact.  Quite possibly we should just remove the timers and enable the rest.

**Comment by macfarla** [comment]
ok thanks @fab-10 and @ajsutton - that gives us somewhere to start!

**Comment by macfarla** [comment]
There are 4 timers, 2 gauges and rollbackCount
  public RocksDBMetrics(
      final OperationTimer readLatency,
      final OperationTimer removeLatency,
      final OperationTimer writeLatency,
      final OperationTimer commitLatency,
      final Counter rollbackCount) {
...
RocksDbMetricsFactory also creates
gauge
        "rocks_db_table_readers_memory_bytes",
        "Estimated memory used for RocksDB index and filter blocks in bytes",
gauge
        "rocks_db_files_size_bytes",
        "Estimated database size in bytes",

And in BesuMetricCategory we explicitly exclude all the RocksDb metrics

    // Why not KVSTORE_ROCKSDB and KVSTORE_ROCKSDB_STATS, KVSTORE_PRIVATE_ROCKSDB_STATS,
    // KVSTORE_PRIVATE_ROCKSDB_STATS?  They hurt performance under load.

**Comment by macfarla** [comment]
@fab-10 would it make sense to remove the timers altogether, or would it make more sense to move them to a separate category that can still be enabled when troubleshooting?

**Comment by fab-10** [comment]
I think we should always have the data about the latency, that is exposed by the timers, but if the comment says that collecting stats has a non negligible side effect on performance, then I am afraid that these stats could not be useful at all, because they could modify the behaviour of Besu. cc: @ahamlat on which is a tollerable overhead for collecting metrics.

At this point I am thinking that a refactor could be required to reduce the overhead of these metrics collection, another option is to leverage the stats that RocksDB dump on its logs at regular intervals, that as last resort could be also delegated to an external process.

**Comment by macfarla** [comment]
Discussed with @ahamlat and it makes sense to prioritise this with his work. Removing from TeamRevenant backlog.

**Comment by non-fungible-nelson** [comment]
@ahamlat - what is the status of this feature story?

**Comment by ahamlat** [comment]
RocksDB metrics are now available in Besu Full Dashboard
