### ISSUE TITLE
eth_chainId API

### ISSUE THREAD

**Issue by jflo** [hyperledger/besu#3562]
### Description
A new endpoint eth_chainId needs to be created, which returns the chain id as uint.

https://github.com/ethereum/execution-apis/blob/188589473adb07a48f11fcb0d687d159e790b8a4/src/eth/client.json#L15

needed for Kiln v2.1

**Comment by daniellehrner** [comment]
In the v2.1 spec it seems like it is a new endpoint, but in reality it isn't. There was an EIP a long time ago, which specified the endpoint: https://eips.ethereum.org/EIPS/eip-695

We have this [already implemented](https://besu.hyperledger.org/en/stable/Reference/API-Methods/#eth_chainid). 
In the current implementation we return a hex value, which is correct because `uint` is indeed a hex value per spec: https://github.com/ethereum/execution-apis/blob/188589473adb07a48f11fcb0d687d159e790b8a4/src/schemas/base-types.json#L42
