### ISSUE TITLE
Alias for --engine-rpc-http-port

### ISSUE THREAD

**Issue by jmcruz1983** [hyperledger/besu#3931]
After upgrading to besu `22.4.1`,
I get following error
```
Unknown option: '--engine-rpc-http-port=8550'
Possible solutions: --engine-rpc-enabled, --engine-rpc-port, --engine-jwt-secret, --engine-jwt-enabled, --engine-host-allowlist

To display full help:
besu [COMMAND] --help
Stream closed EOF for staking/besu-node-0 (besu-node)
```
No breaking changes in the release notes mentioned about

Can you add an alias for `--engine-rpc-http-port`?
Thanks

**Comment by daniellehrner** [comment]
This flag has been removed. The specification of the engine APIs has changed and now only one port, 8551, is used. 8551 can handle HTTP and WS connections, so only one port is needed. Because of this, I don't think it makes sense to create an alias for `--engine-rpc-http-port`, as it has been replaced by `--engine-rpc-port`. But we will definitely take more care in the future to document changes like this as breaking changes in the release notes.

Also in `22.4.1` this port is unauthenticated by default, but in the latest release `22.4.2` is authenticated via JWT per default. Would it be possible to directly use `22.4.2`? Like this a future cli config change can be avoided.
