### ISSUE TITLE
What is Q in QBFT in hyperledger besu?

### ISSUE THREAD

**Issue by esumit** [hyperledger/besu#4016]
I read through all specifications of https://entethalliance.github.io/client-spec/qbft_spec.html, and also https://besu.hyperledger.org/en/stable/

It talks about QBFT, but nowhere exactly mentioned what is Q?
BFT is for Byzantine Fault Tolerant, Assuming Q means Quorum here?

**Comment by siladu** [comment]
Hi @esumit, not sure this is the official answer but yes I would say it stands for Quorum. 
QBFT is implemented by both Besu and [GoQuorum](https://consensys.net/docs/goquorum/en/latest/configure-and-manage/configure/consensus-protocols/qbft/) and both these products are part of the [Quorum](https://consensys.net/quorum/faq/) product suite.

That means you could run a mixed network of Besu and GoQuorum nodes, should you wish, because they interoperate when using QBFT.

**Comment by esumit** [comment]
Thanks @siladu
