### ISSUE TITLE
Wrong estimated value when using estimateGas API

### ISSUE THREAD

**Issue by JosephK95** [hyperledger/besu#4244]
### Description
When we execute `estimateGas` API on a smart contract call, it seems that Besu returns a wrong estimated value.

### Steps to Reproduce (Bug)
1. Download the following file and untar it:
[test_gas_estimation.tar.gz](https://github.com/hyperledger/besu/files/9295689/test_gas_estimation.tar.gz)
2. Execute Besu binary with the following flags:
`besu --data-path test_gas_estimation/data-besu --genesis-file test_gas_estimation/besu.json --rpc-http-port 8549 --rpc-http-enabled --rpc-http-api ETH --network-id 15 --discovery-enabled false`
3. Execute the test case file: `node test1.js`

**Expected behavior:**
All other client implementations return 34165.

**Actual behavior:** 
Only Besu returns 36465.

**Frequency:**
Always

### Versions (Add all that apply)
* Software version: besu/v22.4.4/linux-x86_64/openjdk-java-16
* OS Name & Version: Ubuntu 20.04.4 LTS
* Node.js / web3.js versions: v16.15.0 / v1.7.3

### Smart contract information (If you're reporting an issue arising from deploying or calling a smart contract, please supply related information)
* Solidity version: v0.8.13
* The contract code is provided in the tar.gz file above.
* The contract is deployed at the following address: 0xAe7405782dcf9Fc759020045E7Acc0795d372bc8

**Comment by NickSneo** [comment]
Hey @JosephK95 ,
Can you plz mention which all other client implementations you used and version, it will help in verifying and debugging this.

**Comment by NickSneo** [comment]
Hey,
I have been working on this bug. Updating my findings here - 

Its not just an issue with eth_estimateGas api but with the amount of gas consumed by besu and other eth client like geth.
Here I chose geth for the comparison everywhere.

To reproduce the error, I started dev networks for both besu and geth and deployed a new simple smart contract, and interacted with it. For each step I noted the gas consumed.

simple HelloWorld contract - 
```
// SPDX-License-Identifier: GPL-3.0
pragma solidity ^0.8.0;

contract HelloWorld {
    string greetings;
    function set(string memory greet) public {
        greetings = greet;
    }
    function retrieve() public view returns (string memory){
        return greetings;
    }
}
```

For deploying contract gas consumed by 
geth = 410868
besu = 492040

For calling set function with param = "Hello",
Geth = 45196
Besu = 43868

I have compared all the OPCODEs and their static and dynamic gas cost, everything seems fine to me.
Any suggestions or leads will be helpful, thanks!

**Comment by antonydenyer** [comment]
I could be wrong but I think it is impossible to implement `eth_estimateGas` and get the same result as what geth produces when using a tracer. The reason for this is that geth will perform a binary search with different gas limits until it finds the boundary of a success and failure. 

I think at best you can do with a tracer is safely provide is the minimum guaranteed gas required to complete the transaction, primarily because of the 2300 stipend and the 63/64 rule. Happy to be proven wrong!

**Comment by NickSneo** [comment]
Hey @antonydenyer ,

You are right in Besu the `eth_estimateGas` returns - `return ((long) ((gasUsedByTransaction + gasStipend) * subCallMultiplier));`
In this the gas stipend is 2300 and subCallMultiplier - `Math.pow(64/65, operationTracer.getMaxDepth());`

I am not much sure how geth estimate the gas but through my experiments the estimated value returned by geth was always equal to actual gas consumption by the transaction. 

Now if remove the extra gas stipend of 2300 from besu's gas estimation calculations then it will return `gasUsedByTransaction` and this seems to be the exact gas consumed by the transaction and also equal to geth's estimated gas. (*After some fixes)

I am sure the extra gas stipend and 63/64 rule is an expected behaviour of besu and it is better to leave it as it is.

*But here during my testing I found an interesting bug in Besu that is **difference in actual transaction gas consumption when compared to geth and remix VM** which I have mentioned in my above comment too.
I was able to fix this behaviour in my PR - #5116 ( It seemed some OPCODEs were commented in gas consumption code, by uncommenting those the difference in actual tx gas consumption is fixed)

**Comment by shemnon** [comment]
> *So here during my testing I found an interesting bug in Besu that is difference in actual transaction gas consumption when compared to geth and remix VM which I have mentioned in my above comment too.
I was able to fix this behaviour in my PR - https://github.com/hyperledger/besu/pull/5116 ( It seemed some OPCODEs were commented in gas consumption code, by uncommenting those the difference in actual tx gas consumption is fixed)

Post a test case.  The VM passes all reference tests. I am skeptical that the proposed change actually does what is claimed and need a test case.

**Comment by NickSneo** [comment]
For reference pasting link for test script here - https://github.com/hyperledger/besu/pull/5116#issuecomment-1445896269
