### ISSUE TITLE
Besu takes too much to shutdown

### ISSUE THREAD

**Issue by fab-10** [hyperledger/besu#4313]
### Description

On network with the merge enabled, Besu takes many seconds to stop, for example:

```
# time service besu stop

real    0m31.088s
user    0m0.008s
sys     0m0.002s
```

without the merge enabled it was faster.

Depending on the setup taking to much to stop could result in the process being killed and depending on what Besu was doing, it could cause data inconsistencies.

### Acceptance Criteria

Besu should only few seconds to stop 

### Steps to Reproduce (Bug)

Start Besu on a network with the merge enabled, i.e. Goerli, let it finish the bootstrap step, and then stop it

**Frequency:** [What percentage of the time does it occur?]

Always

### Versions (Add all that apply)
* Software version: 22.7.1
* Java version: "11.0.16"
* OS Name & Version: Ubuntu 22.04.1 LTS

**Comment by fiah84** [comment]
it looks to me like this is caused by failing to shutdown the "PoWMinerExecutor"

Aug 31 03:12:04 ethnode systemd[1]: Stopping Besu Execution Layer Client service...
Aug 31 03:12:14 ethnode besu[80296]: 2022-08-31 03:12:14.635+02:00 | vert.x-eventloop-thread-0 | WARN  | EngineExchangeTransitionConfiguration | not called in 120 seconds, consensus client may not be connected
Aug 31 03:12:25 ethnode besu[80296]: 2022-08-31 03:12:25.667+02:00 | EthScheduler-Timer-0 | INFO  | FullSyncTargetManager | No sync target, waiting for peers. Current peers: 5
Aug 31 03:12:30 ethnode besu[80296]: 2022-08-31 03:12:30.668+02:00 | EthScheduler-Timer-0 | INFO  | FullSyncTargetManager | No sync target, waiting for peers. Current peers: 6
Aug 31 03:12:34 ethnode besu[80296]: 2022-08-31 03:12:34.983+02:00 | BesuCommand-Shutdown-Hook | **ERROR | AbstractMinerExecutor | Failed to shutdown PoWMinerExecutor.**
Aug 31 03:12:34 ethnode besu[80296]: 2022-08-31 03:12:34.988+02:00 | BesuCommand-Shutdown-Hook | INFO  | DefaultSynchronizer | Stopping synchronizer
Aug 31 03:12:34 ethnode besu[80296]: 2022-08-31 03:12:34.992+02:00 | BesuCommand-Shutdown-Hook | INFO  | NetworkRunner | Stopping Network.
Aug 31 03:12:35 ethnode besu[80296]: 2022-08-31 03:12:35.012+02:00 | BesuCommand-Shutdown-Hook | INFO  | EthProtocolManager | Stopping eth Subprotocol.
Aug 31 03:12:35 ethnode besu[80296]: 2022-08-31 03:12:35.020+02:00 | BesuCommand-Shutdown-Hook | INFO  | EthProtocolManager | eth Subprotocol stopped.
Aug 31 03:12:35 ethnode besu[80296]: 2022-08-31 03:12:35.020+02:00 | BesuCommand-Shutdown-Hook | INFO  | NetworkRunner | Network stopped.
