### ISSUE TITLE
AbstractAltBnPrecompiledContract | Native alt bn128 not available

### ISSUE THREAD

**Issue by alptolga** [hyperledger/besu#4367]
After I added the static-nodes.json file I got this warning. Can you help me?

2022-09-08 18:46:40.140+03:00 | main | INFO  | AbstractAltBnPrecompiledContract | Native alt bn128 not available
@shemnon

****Software version:**
besu 22.7.1

**Java version:**
openjdk version "11.0.16" 2022-07-19
OpenJDK Runtime Environment (build 11.0.16+8-post-Ubuntu-0ubuntu118.04)
OpenJDK 64-Bit Server VM (build 11.0.16+8-post-Ubuntu-0ubuntu118.04, mixed mode, sharing)

**OS Name & Version:**
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.6 LTS"
NAME="Ubuntu"
VERSION="18.04.6 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.6 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

**Kernel Version:**
Linux srv 5.6.17-050617-generic #202006071230 SMP Sun Jun 7 12:35:03 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by shemnon** [comment]
The standard bug template asks for this info:

### Versions (Add all that apply)
* Software version: [`besu --version`]
* Java version: [`java -version`]
* OS Name & Version: [`cat /etc/*release`]
* Kernel Version: [`uname -a`]
* Virtual Machine software & version: [`vmware -v`]
* Docker Version: [`docker version`]
* Cloud VM, type, size: [Amazon Web Services I3-large]

The critical one being OS name and version.  Typically this error is seen when attempting to run Besu on Windows.  We don't compile the native libraries on windows (mostly because none of the maintainers are windows devs).

**Comment by non-fungible-nelson** [comment]
closing for @shemnon's response.
