### ISSUE TITLE
IBFT Invalid Block Header (BftProcessorExecutor-IBFT-0 | ERROR | MainnetBlockValidator | Invalid block header. Block 445840)

### ISSUE THREAD

**Issue by daragao** [hyperledger/besu#4440]
### Description
I am currently running a private network of Besu nodes with IBFT 2.0 and gas cost to 0. For an unknown reason the nodes started accumulating pending transactions, after some time a bad block header is propagated (but not mined).

After restarting the network, the problem is resolved.

- What are the reasons why this might be happening?
- In which situations is an invalid block header is created (having into account that all validators are well behaved)?

### Versions (Add all that apply)
*Besu v22.7.1
* oracle-java-11
* Linux CentOS

### Additional Information (Add any of the following or anything else that may be relevant)
* Besu setup info - genesis file, config options
* System info - memory, CPU

### Logs:
Error on my 4 validators: [besu_invalid_block.md](https://github.com/hyperledger/besu/files/9645665/besu_invalid_block.md)
Single node pending tx accumulating and resulting on Bad Block Header error: [pending_tx_bad_block.md](https://github.com/hyperledger/besu/files/9645668/pending_tx_bad_block.md)

I am happy to provide any more info that might be helpful to debug what has happened, I am not able to reproduce it.

**Comment by jframe** [comment]
Hi daragao,

Apologies for only just getting back to you now with this.

It's not clear from the logs why the pending transactions are accumulating. The node that has pending transactions is this one of the proposer nodes? Is it possible get some logs from the proposer nodes?

The invalid block might not be related to the pending transactions issue. The invalid block in this case was caused by a block being created with block with an invalid header timestamp. It had a timestamp that was only 1 second newer than the parent block instead waiting the 2 seconds before proposing the block. This could happen for a few reasons. One could be that there was some time drift on the proposer node and it was slightly of sync with the other nodes. There also the accuracy of the Java timer also can vary and it depends on the OS system timer which can sometimes vary. Both which are not possible for Besu to control.

If this happens and a invalid block is created then a round change will be triggered. I can see in the logs the roundchange occurred and the network was able to continue.

**Comment by siladu** [comment]
@daragao please see @jframe's response above. We will close this issue in a week if no response.

**Comment by daragao** [comment]
can be closed. Understood the issue. 
Block time too short.

**Comment by siladu** [comment]
Thanks for letting us know @daragao :)
