### ISSUE TITLE
tx-pool-hashes-max-size option not being acted upon

### ISSUE THREAD

**Issue by benjaminion** [hyperledger/besu#4496]
### Description
As a mainnet staker, I want to increase the transaction pool size to see if it improves Besu's very poor rate of inclusion of transactions in blocks with its default settings.

The [default](https://besu.hyperledger.org/en/stable/public-networks/reference/cli/options/#tx-pool-max-size) for `tx-pool-hashes-max-size` is 4096, and I constantly see the Tx pool butting up against that limit in my metrics (`besu_transaction_pool_transactions`).

I wanted to try a modest increase to 6144, so added a line to my config file:

```
tx-pool-hashes-max-size=6144
```

However, after restarting the `besu_transaction_pool_transactions` metric continues to sit at or just below 4096. It never exceeds 4096. I am confident that the config file was picked up as Besu recognised a different change I made to it at the same time.

### Acceptance Criteria
* Chainging `tx-pool-hashes-max-size` results in a corresponding change to the size of the transaction pool.

### Steps to Reproduce (Bug)
1. Run Besu on mainnet with `tx-pool-hashes-max-size=6144`
2. Observe that the size of the transaction pool never exceeds the default value of 4096.

I tried once with

```
tx-pool-hashes-max-size=6144
```

And once with

```
tx-pool-hashes-max-size="6144"
```

Neither was effective.

### Versions (Add all that apply)
* Software version: besu/v22.7.5/linux-x86_64/openjdk-java-17

**Comment by macfarla** [comment]
Hi @benjaminion tx-pool-hashes-max size is deprecated - I think you might be looking for the tx-pool-max-size option
https://besu.hyperledger.org/en/stable/public-networks/reference/cli/options/#tx-pool-max-size

I've actioned removing the deprecated option from docs and code - it's been deprecated since 22.1.3
https://github.com/hyperledger/besu/blob/main/CHANGELOG.md#2213

https://github.com/hyperledger/besu-docs/pull/1189
https://github.com/hyperledger/besu/pull/4501

**Comment by benjaminion** [comment]
Oops, you are absolutely right. My copy-paste error.

Can confirm that with the correct option it is working as expected.

Thanks! Closing.
