### ISSUE TITLE
Support web3js contract API 

### ISSUE THREAD

**Issue by MadelineMurray** [hyperledger/besu#504]
As a user, I want to be able to interact with private contracts in the same way as public contracts when using web3js-eea. Where possible, I want web3js-eea to detect when a contract is private and just work.

webj3 doc - https://web3js.readthedocs.io/en/v1.2.0/web3-eth-contract.html

**Comment by MadelineMurray** [comment]
Question for planning session - is this a Besu change or a web3js-eea change?

**Comment by RafaelAPB** [comment]
Hello. Is there anyone working on this issue?

**Comment by MadelineMurray** [comment]
hi @RafaelAPB - no one is working on this currently and this enhancement isn't on our short term roadmap.  If you (or anyone else) wanted to contribute an implementation, we'd be happy to help you get started.

Alternatively, if can want to provide some context about your use-base/business need, we may be able to suggest how this could be solved with our current functionality.

**Comment by RafaelAPB** [comment]
@MadelineMurray thanks for your response. Essencialy, I have a [Besu test ledger running](https://hub.docker.com/r/hyperledger/cactus-besu-all-in-one/dockerfile), I'm [creating a simple contract](https://gist.github.com/RafaelAPB/3828bf5fb48f9d89e73b415a725b8f2e), issuing transactions, and then trying to fetch the contract storage, via this.web3.eth.getStorageAt. That's when I always obtain 0x0 for all variables and constants. I believe this is because of the private transaction feature of Besu. Furthermore, I believe that "the private equivalent of https://web3js.readthedocs.io/en/v1.2.0/web3-eth-contract.html hasn't been implemented yet", which may correspond to this issue. Any thoughts on that?

**Comment by MadelineMurray** [comment]
@RafaelAPB - you're right, the private equivalent of https://web3js.readthedocs.io/en/v1.2.0/web3-eth-contract.html hasn't been implemented yet.  You can use [priv_call](https://besu.hyperledger.org/en/stable/Reference/API-Methods/#priv_call) to access private state.  It can also be invoked from the [web3js-eea library](https://pegasyseng.github.io/web3js-eea/latest/EEAClient.html#~call).

**Comment by MadelineMurray** [comment]
Moved to webjs-eea repo -> https://github.com/PegaSysEng/web3js-eea/issues/139
