### ISSUE TITLE
Private transactions with IBFT logs nonce error

### ISSUE THREAD

**Issue by MadelineMurray** [hyperledger/besu#514]
Sending a private transaction without a nonce using EthSigner + Besu + Orion logs a transaction nonce is lower than sender account nonce. The transaction looks to have been executed correctly though as I can retrieve the transaction receipt using priv_getTransactionReceipt.

```2020-02-03 16:54:17.048+10:00 | pool-10-thread-1 | ERROR | PrivacyPrecompiledContract | Failed to process private transaction 0x158b55d5890664a4656274607951a648b80071ccf36c94e2636f30f3202c2184: Private Transaction nonce 2, is lower than sender account nonce 3.```

To reproduce:

Setup EthSigner, Besu using privacy as a single IBFT node and Orion
Create privacy group using priv_createPrivacyGroup
Send transaction without a nonce through EthSigner with eea_sendTransaction
Can get the contents of the transaction receipt using the transaction hash, but there is a log error "Transaction nonce x, is lower than sender account nonce y.
 
Probability: Probable 
Severity: Moderate 

Originally raised by @jframe

**Comment by MadelineMurray** [comment]
User marlow on RocketChat is also experiencing this - https://chat.hyperledger.org/channel/besu?msg=nok8TMsggJEDp4a2w

**Comment by MadelineMurray** [comment]
@pinges to try and reproduce with latest version.

**Comment by MadelineMurray** [comment]
Check if EthSigner has a retry mechanism - maybe the same transaction is getting sent twice?

**Comment by MadelineMurray** [comment]
Can we reproduce without EthSigner.

**Comment by magooster** [comment]
I can reproduce this error with the web3js-eea library when using the web3.eea.sendRawTransaction method without passing a nonce.

Due to the way web3.eea.sendRawTransaction generates the tx nonce
It uses web3.priv.getTransactionCount call, so if you generate multiple txs in quick succession they will use the same nonce

Whilst they pass pre validation check, they fail during block processing (One will be processed, the others sharing the nonce will fail with a nonce too low error)

**Comment by pinges** [comment]
This behaviour is expected. If you are sending multiple private transactions for the same account ("from") to the same privacy group with the same nonce, only the first transaction will succeed, the other transactions will fail because the nonce is too low. 
EthSigner is using priv_getTransactionCount to set the nonce (if it is not provided in the private transaction). priv_getTransactionCount will result in the same nonce until the private state of the privacy group is updated.    
If it is required that multiple private transactions are sent to the same privacy group using the same account within a short timeframe the nonce management cannot be done by EthSigner. 
EthSigner does have a  retry mechanism for nonce too low errors, but that does not work for private transactions.
This issue should be closed.
We should open an issue against EthSigner to support nonce too low retries for private transactions as well.

**Comment by MadelineMurray** [comment]
Raised https://github.com/PegaSysEng/ethsigner/issues/257 re EthSigner not having a retry mechanism. 

@jframe - see above comments.  Are you happy for this to be closed?
