### ISSUE TITLE
Refactor privacynode.getTransactionSigningKey

### ISSUE THREAD

**Issue by MadelineMurray** [hyperledger/besu#516]
This method should return the privacy signing key rather than pantheon keypair.

Currently, the pantheon keypair is the privacy signing key in all the acceptance tests but they could potentially be different.

**Comment by pinges** [comment]
This method does return a signing key that has been set against the privacy node. 
This key is used in a lot of ATs because it usually does not matter which key is used to sign a private transaction. 
In cases where the signing key used does matter we do usually pick certain ones, e.g. a key that is not the owner of an on-chain privacy group.
Signing keys in general (public or private TXs) are not bound to a certain node. I think this method is more like a convenience method to have a signing key available.
I would propose that we keep this method as it is and close the issue.
