### ISSUE TITLE
Add JSON-RPC method to set target block gas limit

### ISSUE THREAD

**Issue by timbeiko** [hyperledger/besu#544]
As a user, I want to be able to change the block gas limit while Besu is running. Using the `--target-gas-limit` option requires starting and stopping Besu.

Acceptance criteria: Add a JSON-RPC API methods (`admin_changeTargetGasLimit`) to update the target gas limit.

**Comment by RatanRSur** [comment]
@asing177 Hi Aditya! I'm sorry I missed your message last year on gitter. I never really check it. Are you still interested in this?

**Comment by terrencecooke** [comment]
I'm new to Besu, but I've been studying the code base and I would like to work on this issue.

**Comment by RatanRSur** [comment]
@terrencecooke Thanks terrance! Take a look at other `admin_` rpc files for some patterns you can follow

**Comment by terrencecooke** [comment]
Thanks Ratan! After going through the JsonRpcMethods, the code seems more readily designed to have this new command added as a Miner rpc method, rather than an admin.  Miner rpc methods have passed in to them the miningCoordinator, which has executor as a member, which in turn holds the gasLimitCalculator where the targetGasLimit is stored.  The admin rpc methods don't seem to have access to the targetGasLimit.  If there is a way to do it through admin rpc methods, it would be a far more round about way compared to miner rpc methods.

**Comment by terrencecooke** [comment]
Having trouble with the build.  I added the line:
"import org.hyperledger.besu.controller.GasLimitCalculator;" to file:
/besu/ethereum/blockcreation/src/main/java/org/hyperledger/besu/ethereum/blockcreation/AbstractMinerExecutor.java

When I run ./gradlew build, is get the error:
Task :ethereum:blockcreation:compileJava FAILED
.../besu/ethereum/blockcreation/src/main/java/org/hyperledger/besu/ethereum/blockcreation/AbstractMinerExecutor.java:27: 
**error: package org.hyperledger.besu.controller does not exist** 
import org.hyperledger.besu.controller.GasLimitCalculator;

I'm not a gradle build expert, but I think I probably need to add something to the /besu/ethereum/blockcreation/build.gradle file. Does anyone have any ideas to help me along here?

**Comment by RatanRSur** [comment]
When I try to add the import, intellij tells me that I'm creating a circular dependency. If you need to move something to a common anscestor project so that two projects can depend on that, that's fine. If you're using intellij, I believe it can do this for you.
