### ISSUE TITLE
Incorporating Hive into CI/CD

### ISSUE THREAD

**Issue by non-fungible-nelson** [hyperledger/besu#5626]
Incorporating Hive testing into the Besu CI/CD --> GHA.

**Comment by non-fungible-nelson** [comment]
Solution / results need to be available to all Besu contributors

**Comment by macfarla** [comment]
Note Fabio wrote a [script](https://gist.github.com/fab-10/2dc6398b284271afdaeb14a508ddd344) that will spit out new failures since last time the script was run. We should be able to use GHA to run and possibly format the results.

(Also investigate then sending to sonarqube as a custom quality gate.)

Script uses sqlite and curl and that's about it.

**Comment by macfarla** [comment]
closing this as we're going to handle this without directly integrating into Besu CI/CD
