### ISSUE TITLE
Unclear presentation of the new release

### ISSUE THREAD

**Issue by RogerHKW** [hyperledger/besu#6031]
There are 3 things that I don't understand in the [text of your new release](https://github.com/hyperledger/besu/releases/tag/23.10.0). I can't update because of that.

1. You cite several times "# 5772" but clicking the tag doesn't work in this text when I want to learn more about this change.

2.
> `tx-pool-retention-hours`: simply remove it, since it is not applicable in the Layered txpool, old transactions will eventually expire when the memory cache is full.

Isn't there a vulnerability here? By mistake (or with the goal to disturb all Besu nodes of the network), it can happen that accounts send transactions with nonces far enough in the future (up to +199) and, if the gas price is reasonable, these transactions will slowly start to clog our 2nd and 3rd layers, potentially squatting our pools forever if these accounts get abandoned before they reach such nonces.

3. 
> --Xlayered-tx-pool-layer-max-capacity, --Xlayered-tx-pool-max-prioritized and --Xlayered-tx-pool-max-future-by-sender just drop the X and keep the same behavior

It contradicts what is written before. In the text above this paragraph, what seems to be dropped is _Xlayered-_. So, what should I drop to make sure that Besu understands my settings?

**Comment by non-fungible-nelson** [comment]
@fab-10 will address questions 2 and 3 , thanks for these. I have fixed question number 1.

**Comment by fab-10** [comment]
> > `tx-pool-retention-hours`: simply remove it, since it is not applicable in the Layered txpool, old transactions will eventually expire when the memory cache is full.
> 
> Isn't there a vulnerability here? By mistake (or with the goal to disturb all Besu nodes of the network), it can happen that accounts send transactions with nonces far enough in the future (up to +199) and, if the gas price is reasonable, these transactions will slowly start to clog our 2nd and 3rd layers, potentially squatting our pools forever if these accounts get abandoned before 
they reach such nonces.

Let's call these txs _nonce-gapped_, since they are not candidate for selection, due to the fact that for the same sender,  preceding tx is missing, and thus introduces a nonce gap.
Actually, one of the goals of this implementation is to avoid that those _nonce-gapped_ txs will clog the txpool, and prevent other new txs to be added. 
Let me describe how we achieve this property with the new implementation, detailing the lifecycle of a _nonce-gapped_ tx: 

- when we try to add it to the txpool we detected the nonce gap, and this means that it skips both the prioritized and the ready layers (since these layers only accept txs that are sequential with no gaps), so it directly goes to the sparse layer. 
- the sparse layer keeps track of all the gaps, and it will only promote a tx if has no more a gap
- when the sparse layer if full, it starts evicting txs from the oldest
- thus a _nonce-gapped_ tx will always live in the sparse layer, until there is no more space and eventually it gets evicted, or the gap is filled and can be promoted, think of it like a _purgatory_ for those kind of txs.
- at the same time the prioritized and the ready layers are always free of these non-executable txs
- even in the case the txpool is full, when a new sequential executable tx arrives in the pool, it will gets added even if the price is lower that all _nonce-gapped_ txs, because we prefer executable txs and the space for it is recovered evicting the older sparse tx
- so instead of regularly evict old txs, we evict them when the txpool is full, actually trying to fully utilize the space reserved for it

Test performed have confirmed that the layered implementation is much more robust than the legacy in preventing _nonce-gapped_ txs from harming the txpool, if there is space they could be there for a long time, but will never prevent new good txs from being added and confirmed.

Hope this helps, the description in the release was necessarily high level, but I am happy to describe the details of the implementation, and hear about possible issues. 

> 
> > --Xlayered-tx-pool-layer-max-capacity, --Xlayered-tx-pool-max-prioritized and --Xlayered-tx-pool-max-future-by-sender just drop the X and keep the same behavior
> 
> It contradicts what is written before. In the text above this paragraph, what seems to be dropped is _Xlayered-_. So, what should I drop to make sure that Besu understands my settings?

You are right, indeed there is an error in this section, and the right options are the ones above, will update the changelog, thanks.
