### ISSUE TITLE
Does Besu compatible with bundler and ERC-4337?

### ISSUE THREAD

**Issue by suraneti** [hyperledger/besu#6145]
### Description
I've tried various bundlers like eth-infinitism/bundler, alto, and skandha, but none seem to work with `Besu 23.4.1`. Additionally, for ERC-4337, I used https://github.com/eth-infinitism/account-abstraction.

However, it works when I test it on Geth node.

**Comment by non-fungible-nelson** [comment]
Can you try on the latest release? I think this was blocked via #5885 which will be shipped in the 23.10.3 release. You can build from Main now and test this though, as that PR was merged. Follow these instructions to build from source: https://wiki.hyperledger.org/display/BESU/Building+from+source

**Comment by suraneti** [comment]
@non-fungible-nelson, I confirm that Besu develop build (`23.10.3`) is compatible with ERC-4334 and supports bundler services like eth-infinitism/bundler and skandha. The root cause lies in the necessity of the debug_traceCall method."

**Comment by non-fungible-nelson** [comment]
Amazing thank you!

**Comment by bhargav55** [comment]
can you share the genesis.json file, userops are getting created but transactions are reverting with "Execution reverted" error

**Comment by latiffetahaj** [comment]
@suraneti, Is ERC-4337 supported in production? For example, when using eth-infinitism/bundler or skandha, bundlers must be run with the --unsafemode flag to work with Besu. This is because Besu lacks certain tracing methods for opcodes and stakes that are available in Geth. However, running with this flag is not ideal for production environments.
