### ISSUE TITLE
Add a new synonym for the `legacy` transaction pool

### ISSUE THREAD

**Issue by matthew1001** [hyperledger/besu#6211]
### Description
As an enterprise user planning to set up a permissioned chain, I want to be able to choose a TX pool that's more suitable to my requirements, and isn't called `legacy` which implies it might be deprecated.

### Acceptance Criteria
A new transaction pool name for what is currently called the `legacy` pool is decided, and either `legacy` or the new name can be set as a value for the `--tx-pool` configuration parameter.

For maintainers and community members to vote on the most suitable term for the pool, I've added a comment for each option that was discussed in the 1[1/28/2023 EMEA/AMER contributor call](https://wiki.hyperledger.org/display/BESU/2023-11-28+Contributor+Call), with a short explanation. People can vote with a thumbs-up on the one they are most happy with and after a week or two I'll raise a PR with the new name.

**Note:** I've included a couple of "anti-suggestions" so people can see some of the options that were generally ruled out in the contributor call discussion. Thumbs-up on this will be taken to mean people agree that they are not suitable.

I've started the ball rolling with a vote for `sequenced`.

**Comment by matthew1001** [comment]
**Suggestion 1:** `sequenced`

**Reasoning:** The `layered` pool primarily describes its implementation, as opposed to any particular use-case, so `sequenced` would be following that precedent. Since the legacy pool has had changes recently to make it more FIFO-like in its behaviour (see for example https://github.com/hyperledger/besu/pull/6106 / https://github.com/hyperledger/besu/pull/6022) and thus a little "fairer" from the point of view of individual senders, `sequenced` describes a little about its implementation and about how TX selection is done.

**Comment by matthew1001** [comment]
**Suggestion 2:** `flat`

**Reasoning:** Similar to comment 1, `flat` describes a little about its implementation without being specific about any particular use-case.

**Comment by matthew1001** [comment]
**Anti-Suggestion:** `enterprise`

**Reasoning for avoiding:** It implies that the `layered` pool isn't suitable for enterprise use-cases, which is not the case.

**Comment by matthew1001** [comment]
**Anti-Suggestion 2:** `trusted`

**Reason for avoiding:** It implies too much about permissioning-like features.

**Comment by fab-10** [comment]
`sequenced` (or `FIFO`) works well in the case it is used in a _gas free_ network, less if there is a gas market, in which case the main order is dictated by the gas price. 
Another use case for this pool, is to be suitable for more `throughput`, at the cost of lowering some anti-DoS protection (this required some more development), since it is to be used on trusted network

It is not simple to find a name that summarize all these feature, and since I see that the development of this pool should target the use cases of gas free (fairness) and private network (throughput w/o spam protection) I am proposing also a new approach to naming, a kind of acronym that could be expanded to cover the different features.
