### ISSUE TITLE
Clique createemptyblock set to false, should allow to sync even if there are empty blocks

### ISSUE THREAD

**Issue by fab-10** [hyperledger/besu#6290]
Found that the `createemptyblocks` option, introduced in https://github.com/hyperledger/besu/pull/6082, prevents syncing a network that had some empty blocks at the beginning, that scenario could happen if a network was created without this option (or with it set to true) and then changed to false.

The validation should only apply when the node is creating a block, but not when the node is syncing/importing existing blocks.

**Comment by jframe** [comment]
That is the expected behaviour, the value for `createemptyblocks` must be the same and was documented with that warning https://besu.hyperledger.org/development/private-networks/how-to/configure/consensus/clique#skip-empty-blocks.

If we don't validate existing blocks then it would be possible for nodes to have a different value for `createemptyblocks` and we could have a network split. I guess could just validate newly imported blocks though including those that are created and imported that might be ok.

Is it necessary to change from having no empty blocks to having empty blocks? A nicer approach rather than removing the header validation would be add a transition for this.
