### ISSUE TITLE
Not ending loop possible with RetryingGetBlockFromPeersTask

### ISSUE THREAD

**Issue by pinges** [hyperledger/besu#6465]
### Description
In the GetBlockFromPeerTask in executeTask the result is completed exceptionally with an IncompleteResultsException if the response from the peer was empty.
This is caught in AbstractRetryingPeerTask in the executeTask() method, which calls the handleError() method on RetryingGetBlockFromPeersTask, which calls the handleError() method on AbstractRetryingSwitchingPeerTask, which in turn calls the handleError() task on AbstractRetryingPeerTask.
In the handleError() task we are calling the isRetryableError() method on RetryingGetBlockFromPeersTask, which returns true `  @Override
  protected boolean isRetryableError(final Throwable error) {
    return super.isRetryableError(error) || error instanceof IncompleteResultsException;
  }`
and then we call the executeTask on GetBlockFromPeerTask, which will use the same peer (if one was assigned) to try the same request again. 
If a peer does not have the block we are asking for it will response with an empty response. 
Eventually all peers will be disconnected because we are reporting a useless response every time.

**Comment by pinges** [comment]
@fab-10 Could you have a look at this issue please. I think you made the empty response retryable to fix an issue.

**Comment by fab-10** [comment]
Looking at the code the not ending loop should not happen, because there is an upper bound to the number of retries that are allowed, that is usually the number of peers, after which `MaxRetriesReachedException` is returned, and the assigned peer is only used on the first try, following tries will use another peer.

Will create a unit test to confirm what I see from the code.

**Comment by macfarla** [comment]
test added to verify this does not happen in practice
