### ISSUE TITLE
compileTestJava does not cover integration tests

### ISSUE THREAD

**Issue by macfarla** [hyperledger/besu#6670]
running `gw compileTestJava` does not pick up compile failures in integration test files

**Comment by macfarla** [comment]
nor does `gw assemble`

**Comment by usmansaleem** [comment]
# How to reproduce:

- Modify an integration test file such as: `ethereum/api/src/integration-test/java/org/hyperledger/besu/ethereum/api/jsonrpc/methods/fork/london/EthCallIntegrationTest.java` and add an invalid statement so that its not a valid Java source any more.
- Run `./gradlew compileTestJava`. It does not seem to compile integration tests.
```
work/besu [main] » ./gradlew compileTestJava
Starting a Gradle Daemon, 2 incompatible Daemons could not be reused, use --status for details

> Task :ethereum:core:compileJava
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
<snip>
BUILD SUCCESSFUL in 1m 54s
111 actionable tasks: 87 executed, 24 up-to-date
```
