### ISSUE TITLE
Investigate CI incorrectly passing code with compilation errors

### ISSUE THREAD

**Issue by mbaxter** [hyperledger/besu#6685]
### Description
For context, see the PR comment [here](https://github.com/hyperledger/besu/pull/6678#discussion_r1513151554).  In summary, CI has been passing, a change is pushed up, and it starts failing on some unrelated code.  The failing code was pushed in a previous PR, and there is a sequence of passing CI checks before it finally fails here due to the [MethodInputParametersMustBeFinal](https://github.com/hyperledger/besu/blob/dbc128f1002d931344c6a94d6d82253f664d92e8/errorprone-checks/src/main/java/org/hyperledger/errorpronechecks/MethodInputParametersMustBeFinal.java#L39-L39) errorprone check.

I tried running the failing gradle task locally at the git commit where it finally failed in CI.  When running locally, the task passed without failure.  It looks like the `-WError` flag should always be applied (see [build.gradle](https://github.com/hyperledger/besu/blob/2b8d44ec77f19c3a0b06406d75c16f073d1eea86/build.gradle#L225-L225)) so not sure why this is passing locally.

We should investigate this CI flakiness and make sure that we're actually enforcing all of the rules in CI consistently.

**Comment by non-fungible-nelson** [comment]
@macfarla for visibility

**Comment by usmansaleem** [comment]
@non-fungible-nelson I've picked up this issue. This resulted in taking out Besu's custom errorprone into its own repo. Also, the class involved, looks like our errorprone check is not always able to pick it, so I've make a small refactoring in it. Will create a PR to cover this and other bits that are uncovered due to upgrading the errorprone. See https://github.com/hyperledger/besu/pull/6692 as well.
