### ISSUE TITLE
Besu allows QBFT changes in the Genesis block, outside of transitions element.

### ISSUE THREAD

**Issue by IvanovVenko** [hyperledger/besu#6812]
Not sure if this is a bug or a desired feature, but using QBFT I  can simply change the value of the "requesttimeoutseconds" parameter in the "config" -> "qbft" section. Of course the change was applied to all of the nodes.
I'd expect the allowed change to be trough transitions, just like the documentation desribes the change for the "blockperiodseconds" value.

Besu version: 24.3

**Comment by non-fungible-nelson** [comment]
[Transitions support a few items.](https://besu.hyperledger.org/private-networks/how-to/configure/consensus/qbft#transitions) 
> For example, you can update the [block time](https://besu.hyperledger.org/private-networks/how-to/configure/consensus/qbft#configure-block-time-on-an-existing-network), [block reward](https://besu.hyperledger.org/private-networks/how-to/configure/consensus/qbft#configure-block-rewards-on-an-existing-network-deployment), [validator management method](https://besu.hyperledger.org/private-networks/how-to/configure/consensus/qbft#swap-validator-management-methods), or [mining beneficiary](https://besu.hyperledger.org/private-networks/how-to/configure/consensus/qbft#configure-the-mining-beneficiary-on-an-existing-network-deployment).

Seems this is not specified in a transition and can be completed in config. 

@jframe @siladu - is this a correct behavior? I know we have made some of these changes to clique consensus.

**Comment by IvanovVenko** [comment]
The point is that:
1. the impelementation of "requesttimeoutseconds" change vs "blockperiodseconds" change is incostistent.  
2. changing "requesttimeoutseconds" this way does not trigger warning (halt) that the Genesis Block has been changed.

**Comment by jframe** [comment]
@IvanovVenko 

1. This is expected as not all the QBFT configuration properties can be modified using transitions. We have only added transition support for some of the QBFT config. If you want support for "requesttimeoutseconds" in QBFT using transitions feel free to raise an issue for this.

2. This is the expected behaviour as the values in the config section of the genesis file are not included in the genesis block. And so changing any of these values in the config section will not give a warning.
