### ISSUE TITLE
EIP-7251

### ISSUE THREAD

**Issue by daniellehrner** [hyperledger/besu#7254]
[EIP-7251](https://eips.ethereum.org/EIPS/eip-7251#execution-layer-1) has added consolidation requests coming from the EL layer. Those requests are the same type as the withdrawal requests from [EIP-7002](https://eips.ethereum.org/EIPS/eip-7002#execution-layer).

* A new consolidation request needs to be created: https://eips.ethereum.org/EIPS/eip-7251#consolidation-request
* A new system contract needs to be deployed: https://eips.ethereum.org/EIPS/eip-7251#bytecode
* A new system call to the contract needs to be implemented: https://eips.ethereum.org/EIPS/eip-7251#system-call
* At the end of the block processing it needs to be checked that the consolidations in the contract, matches the consolidation requests list: https://eips.ethereum.org/EIPS/eip-7251#block-processing

**Comment by lucassaldanha** [comment]
> A new system call to the contract needs to be implemented: https://eips.ethereum.org/EIPS/eip-7251#system-call

Just a note that this system call mechanism is similar to what is used on EIP-7002. However, our current implementation in Besu is not executing the actual contract bytecode, but is "manually" manipulating the contract storage to simulate the system call. Although this achieves the same end results, it is not a good idea as if the contract changes, we need to update our code to reflect that change (instead of just relying on the updated contract code).

My suggestion is to implement the logic to perform system calls and then use the same mechanism for both EIP-7002 and EIP-7251 system calls. 

In terms of implementing system call logic, I think it could be similar to what we do with the TransactionSimulator when we want to process `eth_call`, but with the capability of persisting contract storage changes. But I haven't worked on Besu for a long time so I would take any suggestion I make with a grain of salt.

I believe @Gabriel-Trintinalia was looking at this system call logic at some point and might have more info about it.

**Comment by macfarla** [comment]
waiting for system call PR and the final address & bytecode for the consolidation contract

**Comment by non-fungible-nelson** [comment]
https://github.com/hyperledger/besu/pull/7263 @macfarla
